quality:
  jpg: 85
  png: 85
  webp: 85
strip: true
svgo: true
pngquant:
  quality: [0.65, 0.8]
  speed: 3
mozjpeg:
  quality: 85
  progressive: true
optipng:
  level: 5
svgo:
  plugins:
    - removeViewBox: false
    - removeDimensions: true
    - cleanupIDs: true 